name: Build Windows Forms App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore hhh.csproj

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build Project
      run: msbuild hhh.csproj /p:Configuration=Release

    - name: Prepare Artifacts
      run: |
        mkdir artifacts
        Copy-Item -Path "bin/Release/**/*" -Destination "artifacts" -Recurse -Force

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SystemOptimizer-Build
        path: artifacts
